---
protocol-key-pair: KA44l1WJDHuzVPTsNp6yc9mf3BZeA/81t3tP3QzSUVeQ4nPGT7Lp85M05Nhbeq/vqiu2VBeN0MbG5zayE6XHSzRjUTqLeESZuQ9o56GLnegGFyot0QCYooX1iKFkuh7C3/Mg/C5e2DBUSryzc51mAukzv/Vqgve1gikp8UA0t/o=
worker-key-pair: bBhxj1CDN5q1Qr1wqb1ndC/C42s3DxfRh6x0/f+OBxh7ZMShSZ4ntX8xPn9YEfRZB3/O37+jATbeL3RYTsNyLA==
account-key-pair: ADlvhFQTZyXZhzQHp1q4Za0VOkGIlKdTFAeGhI7X2eQpM8ZNSAqX7HhEHbJyCePLHjDHDSExxoUftVeeQuuGTPw=
network-key-pair: hbFK5aOfpbQrLefRWOVFSUL9P62diGHgeibmwlXikV8EluZ2sQjTSKlzyGrFjpjWdidFG6CqcMhkYApKfGAlRQ==
db-path: /Users/w1q/.sui/sui_config/authorities_db/90e273c64fb2e9f39334e4d85b7aafefaa2bb654178dd0c6c6e736b213a5c74b3463513a8b784499b90f68e7a18b9de806172a2dd10098a285f588a164ba1ec2dff320fc2e5ed830544abcb3739d6602e933bff56a82f7b5822929f14034b7fa
network-address: /ip4/127.0.0.1/tcp/54189/http
json-rpc-address: "127.0.0.1:54243"
websocket-address: ~
metrics-address: "127.0.0.1:54239"
admin-interface-port: 54241
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/54195/http
  consensus-db-path: /Users/w1q/.sui/sui_config/consensus_db/90e273c64fb2e9f39334e4d85b7aafefaa2bb654178dd0c6c6e736b213a5c74b3463513a8b784499b90f68e7a18b9de806172a2dd10098a285f588a164ba1ec2dff320fc2e5ed830544abcb3739d6602e933bff56a82f7b5822929f14034b7fa
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/54229/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/54231/http
    network_admin_server:
      primary_network_admin_server_port: 54233
      worker_network_admin_server_base_port: 54235
enable-event-processing: false
enable-gossip: true
enable-checkpoint: true
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:54237"
genesis:
  genesis-file-location: /Users/w1q/.sui/sui_config/genesis.blob
